// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    TimeScheduler: typeof import('./src/components/TimeScheduler.vue')['default']
    TimezoneSearch: typeof import('./src/components/TimezoneSearch.vue')['default']
  }
}
